### PR TITLE
change theme from light to dark mode

### PR DESCRIPTION
**Pull request by rizki4106**
hello. I've changed its appearance from light to dark by adding a few lines of css code. I hope this is what you want

### CODE REVIEW

**Review by SarthakRana — CHANGES_REQUESTED** [review]
Hi @rizki4106 . This looks amazing. Just 2 small requests :
1. Can you retain the original colors from the previous web app. Like all the colors have changed, specially the plots and world map.
2. Can you provide a toggle button somewhere at the top right/left to switch between white and dark mode.

Thanks

**Comment by rizki4106** [comment]
hi, i have added the toggle button and also made the display color as you want.
i hope you like it

**Review by SarthakRana — CHANGES_REQUESTED** [review]
Colors are still the same :(
Am I missing something here ? Should I send you the screenshots over mail ?

**Comment by rizki4106** [comment]
yes please, rizkimaulana4106@gmail.com

**Comment by SarthakRana** [comment]
I have shared over mail.

**Review by SarthakRana — APPROVED** [review]
Great job @rizki4106 . Thanks for the contribution :)

**Pull request merged**
